## Time series prediction

In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt
import yfinance as yf
from sklearn.metrics import r2_score
from sklearn.ensemble import RandomForestRegressor
from utils import MACD, RSI, Drawdown_current, volatility_rolling, extract, Close_price, log_return, WFCV, feature_engineering_rf, feature_engineering_lstm, feature_engineering_arp, LSTMRegressor, stats_forecasting
import statsmodels.api as sm
from tqdm import tqdm
from IPython.display import display

In [2]:
def WFCV_DL(X, y, model, step_size=50, fold_size=1250): 
    """
    Performs Walk-Forward Cross-Validation for time series modeling.
    
    Iteratively trains the model on a rolling window of size `fold_size` 
    and tests it on the subsequent window of size `step_size`.
    
    Args:
        X (pd.DataFrame): The feature matrix.
        y (pd.Series): The target variable (e.g., log returns).
        model (sklearn-like estimator): The machine learning model to be evaluated.
            Must implement `.fit()` and `.predict()` methods.
        step_size (int, optional): The number of steps (days) to predict in each iteration. Defaults to 50.
        fold_size (int, optional): The number of steps (days) used for training in each iteration. Defaults to 200.
        
    Returns:
        tuple: A tuple containing four elements:
            - predictions (np.ndarray): Array of all concatenated predictions.
            - truths (np.ndarray): Array of all concatenated true target values.
            - mse_tab (np.ndarray): Array of the Mean Squared Error (MSE) computed for each fold.
            - r2 (float): The overall R-squared (R2) score across all predictions.
    """

    predictions = []
    truths = []
    mse_tab = []

    for start in range(0, len(X) - fold_size, step_size):
        train_X = X.iloc[start : start + fold_size] 
        train_y = y.iloc[start : start + fold_size]
        test_X = X.iloc[start + fold_size : start + fold_size + step_size]
        test_y = y.iloc[start + fold_size : start + fold_size + step_size]    

        model.fit(train_X, train_y)
        pred = model.predict(test_X)        
        
        predictions.extend(pred)
        truths.extend(test_y)

        mse = mean_squared_error(test_y, pred)
        mse_tab.append(mse)

    return np.array(predictions), np.array(truths), np.array(mse_tab), r2_score(truths, predictions)

# stats_forecasting 


def stats_forecasting_DL(df_all, name_ticker, model, feature_engineering, step_size = 50, fold_size = 250, plot = True): # plot = True --> show plots and print statements + changer le nom: plus explicite
    """
    Executes the full end-to-end pipeline: data extraction, feature engineering, 
    model training/evaluation (WFCV), and performance analysis.
    
    Args:
        df_all (pd.DataFrame): The complete DataFrame containing all tickers and their returns.
        name_ticker (str): The ticker symbol or column name of the asset to process.
        model (sklearn-like estimator): The model to train and evaluate.
        feature_engineering (function): The function to apply for feature engineering on the DataFrame.
        plot (bool, optional): If True, displays progress prints and matplotlib charts. Defaults to True.
        
    Returns:
        dict: A dictionary containing the evaluation metrics of the model:
            - 'SYMBOL': The processed ticker name.
            - 'MSE': Average Mean Squared Error across all folds.
            - 'OLS_R2': R-squared from the OLS regression (explained variance).
            - 'OLS_Intercept': Intercept of the predictions.
            - 'OLS_Slope': Slope of the predictions.
            - 'OLS_P_Value_Intercept': Statistical significance of the intercept.
            - 'P_Value_Slope': Statistical significance of the slope.
    """

    if plot: print("Processing", name_ticker, '...')

    df = extract(df_all, name_ticker)
    df["Close"] = Close_price(df)
    df["log_return"] = log_return(df)
    df = feature_engineering(df)

    if plot: 
        print("Processing finished")

        print("Data after feature engineering:")
        print(df.head())

        plt.plot(df.index, df['log_return'])
        plt.show()

    X = df.drop(columns=['return', 'log_return', 'Close'])
    y = df['log_return']

    if plot: 
        print("Starting Walk-Forward Cross-Validation...")

    y_pred, y_truth, mse_tab, r2 = WFCV_DL(X, y, model, step_size, fold_size)

    if plot: 
        print("WFCV finished.")

        plt.figure(figsize=(12,6))
        plt.plot(y_truth, label='True Log Returns', color='blue')
        plt.plot(y_pred, label='RF Predicted Log Returns', color='red')
        plt.legend()
        plt.title(f'{name_ticker} Model Predictions vs True Log Returns')
        plt.plot(mse_tab)
        plt.show()

    if plot: 
        print("Computing OLS regression on truth over pred...")

    reg = sm.OLS(y_truth, sm.add_constant(y_pred)).fit()

    if plot: 
        print("Regression complete !")
        print(reg.summary())

    results = {
        'SYMBOL': name_ticker,
        'MSE': np.mean(mse_tab),
        'OLS_R2': reg.rsquared,          
        'OLS_Intercept': reg.params[0],  
        'OLS_Slope': reg.params[1],     
        'OLS_P_Value_Intercept': reg.pvalues[0],
        'P_Value_Slope': reg.pvalues[1],       
    }

    return results

In [3]:
import pandas as pd
from tqdm import tqdm
from joblib import Parallel, delayed
import os

def process_one_ticker(name, df, model, fonc, step_size = 250, fold_size = 21):
    """
    Encapsule la logique pour un seul ticker pour permettre le multi-processing.
    """
    try:
        # On exécute la WFCV sur un ticker
        res = stats_forecasting_DL(df, name, model, fonc, step_size, fold_size, plot=False)
        return res
    except Exception as e:
        # En parallèle, il vaut mieux print l'erreur pour débugger
        # print(f"Erreur sur {name}: {e}")
        return None

In [4]:
df = pd.read_csv('Datasets/returns_all.csv')
df.drop(['KOCRD Index', 'NOBRON Index', 'CABROVER Index', 'EB03/3M Index', 'BZSTSETA Index', 'MXNZ0EN Index', 'EGDIMW Index', 'UX1 Index', 'VXEEM Index', 'VXEFA Index', 'VXEWZ Index', 'VXFXI Index', 'VXGDX Index', 'VXSLV Index', 'W 1 Comdty', 'W1DOW Index', 'WBI Index', 'FNRETTM Index','FNREU Index', 'WIG Index', 'WIGCON Index', 'WIGFOOD Index', 'XU100 Index', 'XUHIZ Index','XUMAL Index', 'XUSIN Index', 'XUTEK Index', 'YW1 Comdty', 'ZAREUR Curncy', 'ZARJPY Curncy', 'ZARUSD Curncy'], axis=1, inplace=True) # on retire les colonnes qui ont peu d'échantillons

all_tickers = df.columns[1:].tolist() 
test_tickers = [
    "GC1 Comdty", 
    "BLQ2TRUU Index", 
    "GBPJPY Curncy", 
    "M4EUHDVD Index", 
    "HFRXM Index", 
    "GB1M Index", 
    "QW2I Index", 
    "FNER Index", 
    "SPX Index" 
]
tickers_name = "test_tickers"

### LSTM

In [5]:
# Prérequis : imports (1), définition de `stats_forecasting` (2). `test_tickers` / `tickers_name` : cellule tickers (valeurs par défaut ci‑dessous si absentes).
_cols_drop = ['KOCRD Index', 'NOBRON Index', 'CABROVER Index', 'EB03/3M Index', 'BZSTSETA Index', 'MXNZ0EN Index', 'EGDIMW Index', 'UX1 Index', 'VXEEM Index', 'VXEFA Index', 'VXEWZ Index', 'VXFXI Index', 'VXGDX Index', 'VXSLV Index', 'W 1 Comdty', 'W1DOW Index', 'WBI Index', 'FNRETTM Index','FNREU Index', 'WIG Index', 'WIGCON Index', 'WIGFOOD Index', 'XU100 Index', 'XUHIZ Index','XUMAL Index', 'XUSIN Index', 'XUTEK Index', 'YW1 Comdty', 'ZAREUR Curncy', 'ZARJPY Curncy', 'ZARUSD Curncy']
df_for_lstm = pd.read_csv('Datasets/returns_all.csv')
df_for_lstm.drop(columns=[c for c in _cols_drop if c in df_for_lstm.columns], axis=1, inplace=True)

if 'test_tickers' not in globals():
    test_tickers = ['GC1 Comdty', 'SI1 Comdty', 'HG1 Comdty']
if 'tickers_name' not in globals():
    tickers_name = "all_tickers"

import pandas as pd
from tqdm import tqdm
from joblib import Parallel, delayed
import os

# --- 1. Optimisation du modèle ---
model_lstm = LSTMRegressor(
    lookback=20,
    lstm_units=16,        
    dropout=0.20,         
    l2_reg=1e-4,          
    max_epochs=50,         # Réduit de 150 à 50 : gain de temps massif
    batch_size=256,        # Augmenté pour traiter plus de données d'un coup
    val_frac=0.15,
    early_stop_patience=8, # Plus réactif : on arrête dès que ça ne progresse plus
    verbose=0,
    random_state=42,
)

model_name_lstm = "LSTM_lb20_fast"
fonc_lstm = feature_engineering_lstm

# --- 3. Exécution Parallèle ---
# n_jobs=-1 utilise tous les processeurs de ton Mac. 
# Si ton Mac surchauffe ou manque de RAM, remplace -1 par 4 ou 2.
print(f"Lancement de l'entraînement parallèle pour {len(all_tickers)} tickers...")

results_lstm = Parallel(n_jobs=-1)(
    delayed(process_one_ticker)(name, df_for_lstm, model_lstm, fonc_lstm, step_size=250, fold_size=1250) 
    for name in tqdm(all_tickers, desc="LSTM — Parallel")
)

# --- 4. Nettoyage et Sauvegarde ---
# On retire les résultats None (ceux qui ont crashé)
results_lstm = [r for r in results_lstm if r is not None]

df_lstm_results = pd.DataFrame(results_lstm)
display(df_lstm_results)

# Sauvegarde sécurisée
os.makedirs('Resultats', exist_ok=True)
df_lstm_results.to_csv(f'Resultats/{"fenetre_5_ans"}/resultats_{tickers_name}_{model_name_lstm}.csv', index=False)

Lancement de l'entraînement parallèle pour 1035 tickers...

LSTM — Parallel:   5%|▍         | 49/1035 [21:01<9:40:54, 35.35s/it] Exception ignored in: <function WeakKeyDictionary.__init__.<locals>.remove at 0x15a08e3e0>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/weakref.py", line 369, in remove
    def remove(k, selfref=ref(self)):

KeyboardInterrupt:

KeyboardInterrupt:

### RF

In [5]:
# Prérequis : imports (1), définition de `stats_forecasting` (2).
# Cette cellule est autonome pour les variables de données / tickers.

try:
    from sklearn.ensemble import RandomForestRegressor
except ImportError as e:
    raise ImportError(
        "scikit-learn n'est pas installé. Installe-le avec `pip install scikit-learn` "
        "puis relance."
    ) from e

_cols_drop = [
    'KOCRD Index', 'NOBRON Index', 'CABROVER Index', 'EB03/3M Index', 'BZSTSETA Index',
    'MXNZ0EN Index', 'EGDIMW Index', 'UX1 Index', 'VXEEM Index', 'VXEFA Index', 'VXEWZ Index',
    'VXFXI Index', 'VXGDX Index', 'VXSLV Index', 'W 1 Comdty', 'W1DOW Index', 'WBI Index',
    'FNRETTM Index', 'FNREU Index', 'WIG Index', 'WIGCON Index', 'WIGFOOD Index', 'XU100 Index',
    'XUHIZ Index', 'XUMAL Index', 'XUSIN Index', 'XUTEK Index', 'YW1 Comdty', 'ZAREUR Curncy',
    'ZARJPY Curncy', 'ZARUSD Curncy'
]

df_for_rf = pd.read_csv('Datasets/returns_all.csv')
df_for_rf.drop(columns=[c for c in _cols_drop if c in df_for_rf.columns], axis=1, inplace=True)

if 'all_tickers' not in globals():
    all_tickers = df_for_rf.columns[1:].tolist()
if 'test_tickers' not in globals():
    test_tickers = ['GC1 Comdty', 'SI1 Comdty', 'HG1 Comdty']
if 'tickers_name' not in globals():
    tickers_name = 'all_tickers'

# --- Configuration du Random Forest avec paramètres équivalents ---
model_rf = RandomForestRegressor(
    n_estimators=500,          # Équivalent n_estimators
    max_depth=5,               # Équivalent max_depth
    min_samples_leaf=5,        # Proche de min_child_weight pour limiter la taille des feuilles
    max_samples=0.8,           # Équivalent subsample (prend 80% des lignes pour chaque arbre)
    max_features=0.8,          # Équivalent colsample_bytree (prend 80% des features)
    random_state=42,           # Équivalent random_state
    n_jobs=-1,                 # Utilisation de tous les cœurs
)
model_name_rf = 'RF_n500_d5'
fonc_rf = feature_engineering_rf

# Note : Si la fonction process_one_ticker utilise déjà le parallélisme en interne, 
# attention aux conflits avec le n_jobs=-1 du RandomForestRegressor (le fameux "nested parallelism").
results_rf = Parallel(n_jobs=-1)(
    delayed(process_one_ticker)(name, df_for_rf, model_rf, fonc_rf, step_size=250, fold_size=1250) 
    for name in tqdm(all_tickers, desc="Random Forest — Parallel")
)

# --- 4. Nettoyage et Sauvegarde ---
# On retire les résultats None (ceux qui ont crashé)
results_rf = [r for r in results_rf if r is not None]

df_rf_results = pd.DataFrame(results_rf)
display(df_rf_results)

# Sauvegarde sécurisée
os.makedirs('Resultats', exist_ok=True)
df_rf_results.to_csv(f'Resultats/{"fenetre_5_ans"}/resultats_{tickers_name}_{model_name_rf}.csv', index=False)

Random Forest — Parallel:  46%|████▌     | 472/1035 [44:15<51:51,  5.53s/it]  /opt/anaconda3/lib/python3.12/site-packages/pandas/core/arraylike.py:399: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
Random Forest — Parallel: 100%|██████████| 1035/1035 [1:30:26<00:00,  5.24s/it]

,SYMBOL,MSE,OLS_R2,OLS_Intercept,OLS_Slope,OLS_P_Value_Intercept,P_Value_Slope
0,ADBF Index,0.000191,0.123159,0.000175,1.116255,0.602515,4.390974e-53
1,ADCM Index,0.000372,0.161800,-0.000137,1.027158,0.783145,4.782831e-63
2,ADCT Index,0.000203,0.109766,0.000370,1.235456,0.282506,5.460798e-47
3,ADEG Index,0.000492,0.077535,0.000376,1.026728,0.507424,2.874186e-30
4,ADII Index,0.000053,0.066818,0.000261,0.903828,0.083504,1.219574e-36
...,...,...,...,...,...,...,...
993,USDDEM Curncy,0.000028,0.076074,0.000017,1.064772,0.809827,1.091791e-94
994,USDEUR Curncy,0.000028,0.086830,-0.000012,1.151878,0.865920,1.520975e-107
995,USDJPY Curncy,0.000034,0.078020,-0.000012,1.007653,0.878039,5.102832e-97
996,FNMRC Index,0.000314,0.012203,0.000535,0.253487,0.095315,1.766743e-09
997,FNR5 Index,0.000322,0.049281,0.000182,1.212350,0.471442,2.868145e-58

In [6]:
# Prérequis : imports (1), définition de `stats_forecasting` (2).
# Cette cellule est autonome pour les variables de données / tickers.

try:
    from sklearn.ensemble import RandomForestRegressor
except ImportError as e:
    raise ImportError(
        "scikit-learn n'est pas installé. Installe-le avec `pip install scikit-learn` "
        "puis relance."
    ) from e

_cols_drop = [
    'KOCRD Index', 'NOBRON Index', 'CABROVER Index', 'EB03/3M Index', 'BZSTSETA Index',
    'MXNZ0EN Index', 'EGDIMW Index', 'UX1 Index', 'VXEEM Index', 'VXEFA Index', 'VXEWZ Index',
    'VXFXI Index', 'VXGDX Index', 'VXSLV Index', 'W 1 Comdty', 'W1DOW Index', 'WBI Index',
    'FNRETTM Index', 'FNREU Index', 'WIG Index', 'WIGCON Index', 'WIGFOOD Index', 'XU100 Index',
    'XUHIZ Index', 'XUMAL Index', 'XUSIN Index', 'XUTEK Index', 'YW1 Comdty', 'ZAREUR Curncy',
    'ZARJPY Curncy', 'ZARUSD Curncy'
]

df_for_rf = pd.read_csv('Datasets/returns_all.csv')
df_for_rf.drop(columns=[c for c in _cols_drop if c in df_for_rf.columns], axis=1, inplace=True)

if 'all_tickers' not in globals():
    all_tickers = df_for_rf.columns[1:].tolist()
if 'test_tickers' not in globals():
    test_tickers = ['GC1 Comdty', 'SI1 Comdty', 'HG1 Comdty']
if 'tickers_name' not in globals():
    tickers_name = 'all_tickers'

# --- Configuration du Random Forest avec paramètres équivalents ---
model_rf = RandomForestRegressor(
    n_estimators=500,          # Équivalent n_estimators
    max_depth=4,               # Équivalent max_depth
    min_samples_leaf=5,        # Proche de min_child_weight pour limiter la taille des feuilles
    max_samples=0.8,           # Équivalent subsample (prend 80% des lignes pour chaque arbre)
    max_features=0.8,          # Équivalent colsample_bytree (prend 80% des features)
    random_state=42,           # Équivalent random_state
    n_jobs=-1,                 # Utilisation de tous les cœurs
)
model_name_rf = 'RF_n500_maxs08_d4'
fonc_rf = feature_engineering_rf

# Note : Si la fonction process_one_ticker utilise déjà le parallélisme en interne, 
# attention aux conflits avec le n_jobs=-1 du RandomForestRegressor (le fameux "nested parallelism").
results_rf = Parallel(n_jobs=-1)(
    delayed(process_one_ticker)(name, df_for_rf, model_rf, fonc_rf, step_size=50, fold_size=250) 
    for name in tqdm(all_tickers, desc="Random Forest — Parallel")
)

# --- 4. Nettoyage et Sauvegarde ---
# On retire les résultats None (ceux qui ont crashé)
results_rf = [r for r in results_rf if r is not None]

df_rf_results = pd.DataFrame(results_rf)
display(df_rf_results)

# Sauvegarde sécurisée
os.makedirs('Resultats', exist_ok=True)
df_rf_results.to_csv(f'Resultats/{"fenetre_1_an"}/resultats_{tickers_name}_{model_name_rf}.csv', index=False)

Random Forest — Parallel:  46%|████▌     | 472/1035 [1:04:51<1:14:41,  7.96s/it]/opt/anaconda3/lib/python3.12/site-packages/pandas/core/arraylike.py:399: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
Random Forest — Parallel: 100%|██████████| 1035/1035 [2:49:50<00:00,  9.85s/it]

,SYMBOL,MSE,OLS_R2,OLS_Intercept,OLS_Slope,OLS_P_Value_Intercept,P_Value_Slope
0,ADBF Index,0.000227,0.042729,0.000411,0.653335,0.147096,2.534867e-28
1,ADCM Index,0.000416,0.107127,0.000354,0.883897,0.378222,7.985972e-66
2,ADCT Index,0.000250,0.069620,-0.000014,0.782770,0.962855,1.403078e-45
3,ADEG Index,0.000559,0.051262,0.000125,0.718810,0.787431,7.875196e-32
4,ADHC Index,0.000856,0.081902,0.003423,1.166296,0.027301,1.013000e-09
...,...,...,...,...,...,...,...
1030,USDDEM Curncy,0.000031,0.038751,-0.000004,0.719518,0.956099,7.752473e-57
1031,USDEUR Curncy,0.000031,0.047803,0.000017,0.784825,0.805385,1.555625e-69
1032,USDJPY Curncy,0.000035,0.053513,0.000140,0.762160,0.060010,2.826059e-78
1033,FNMRC Index,0.000249,0.015724,0.000331,0.430083,0.187358,2.540932e-15
1034,FNR5 Index,0.000286,0.061897,0.000399,0.822247,0.065067,4.248118e-87

In [7]:
# Prérequis : imports (1), définition de `stats_forecasting` (2).
# Cette cellule est autonome pour les variables de données / tickers.

try:
    from sklearn.ensemble import RandomForestRegressor
except ImportError as e:
    raise ImportError(
        "scikit-learn n'est pas installé. Installe-le avec `pip install scikit-learn` "
        "puis relance."
    ) from e

_cols_drop = [
    'KOCRD Index', 'NOBRON Index', 'CABROVER Index', 'EB03/3M Index', 'BZSTSETA Index',
    'MXNZ0EN Index', 'EGDIMW Index', 'UX1 Index', 'VXEEM Index', 'VXEFA Index', 'VXEWZ Index',
    'VXFXI Index', 'VXGDX Index', 'VXSLV Index', 'W 1 Comdty', 'W1DOW Index', 'WBI Index',
    'FNRETTM Index', 'FNREU Index', 'WIG Index', 'WIGCON Index', 'WIGFOOD Index', 'XU100 Index',
    'XUHIZ Index', 'XUMAL Index', 'XUSIN Index', 'XUTEK Index', 'YW1 Comdty', 'ZAREUR Curncy',
    'ZARJPY Curncy', 'ZARUSD Curncy'
]

df_for_rf = pd.read_csv('Datasets/returns_all.csv')
df_for_rf.drop(columns=[c for c in _cols_drop if c in df_for_rf.columns], axis=1, inplace=True)

if 'all_tickers' not in globals():
    all_tickers = df_for_rf.columns[1:].tolist()
if 'test_tickers' not in globals():
    test_tickers = ['GC1 Comdty', 'SI1 Comdty', 'HG1 Comdty']
if 'tickers_name' not in globals():
    tickers_name = 'all_tickers'

# --- Configuration du Random Forest avec paramètres équivalents ---
model_rf = RandomForestRegressor(
    n_estimators=500,          # Équivalent n_estimators
    max_depth=4,               # Équivalent max_depth
    min_samples_leaf=5,        # Proche de min_child_weight pour limiter la taille des feuilles
    max_samples=0.8,           # Équivalent subsample (prend 80% des lignes pour chaque arbre)
    max_features=0.8,          # Équivalent colsample_bytree (prend 80% des features)
    random_state=42,           # Équivalent random_state
    n_jobs=-1,                 # Utilisation de tous les cœurs
)
model_name_rf = 'RF_n500_maxs08_d4'
fonc_rf = feature_engineering_rf

# Note : Si la fonction process_one_ticker utilise déjà le parallélisme en interne, 
# attention aux conflits avec le n_jobs=-1 du RandomForestRegressor (le fameux "nested parallelism").
results_rf = Parallel(n_jobs=-1)(
    delayed(process_one_ticker)(name, df_for_rf, model_rf, fonc_rf, step_size=5, fold_size=21) 
    for name in tqdm(all_tickers, desc="Random Forest — Parallel")
)

# --- 4. Nettoyage et Sauvegarde ---
# On retire les résultats None (ceux qui ont crashé)
results_rf = [r for r in results_rf if r is not None]

df_rf_results = pd.DataFrame(results_rf)
display(df_rf_results)

# Sauvegarde sécurisée
os.makedirs('Resultats', exist_ok=True)
df_rf_results.to_csv(f'Resultats/{"fenetre_1_mois"}/resultats_{tickers_name}_{model_name_rf}.csv', index=False)

Random Forest — Parallel:  46%|████▌     | 472/1035 [24:28:28<9:03:30, 57.92s/it]    /opt/anaconda3/lib/python3.12/site-packages/pandas/core/arraylike.py:399: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
Random Forest — Parallel: 100%|██████████| 1035/1035 [40:41:50<00:00, 141.56s/it]

,SYMBOL,MSE,OLS_R2,OLS_Intercept,OLS_Slope,OLS_P_Value_Intercept,P_Value_Slope
0,ADBF Index,0.000241,0.009195,0.000410,0.276557,0.136328,1.288003e-07
1,ADCM Index,0.000472,0.027600,0.000550,0.461951,0.173646,6.406127e-19
2,ADCT Index,0.000286,0.008333,0.000111,0.243645,0.708568,5.168927e-07
3,ADEG Index,0.000656,0.001942,0.000005,0.124115,0.992137,1.860338e-02
4,ADHC Index,0.000854,0.002722,0.000147,0.149207,0.892696,1.780172e-01
...,...,...,...,...,...,...,...
1030,USDDEM Curncy,0.000036,0.002795,-0.000028,0.155808,0.687212,1.686854e-05
1031,USDEUR Curncy,0.000036,0.002605,-0.000026,0.149068,0.713253,3.471624e-05
1032,USDJPY Curncy,0.000040,0.002422,0.000072,0.143242,0.336921,6.260760e-05
1033,FNMRC Index,0.000280,0.000348,0.000057,-0.052027,0.812796,2.281037e-01
1034,FNR5 Index,0.000306,0.012839,0.000243,0.336697,0.257165,1.295243e-19

### XGBoost

In [ ]:
# Prérequis : imports (1), définition de `stats_forecasting` (2).
# Cette cellule est autonome pour les variables de données / tickers.

try:
    from xgboost import XGBRegressor
except ImportError as e:
    raise ImportError(
        "xgboost n'est pas installé. Installe-le avec `pip install xgboost` "
        "(ou `conda install -c conda-forge py-xgboost`) puis relance."
    ) from e

_cols_drop = [
    'KOCRD Index', 'NOBRON Index', 'CABROVER Index', 'EB03/3M Index', 'BZSTSETA Index',
    'MXNZ0EN Index', 'EGDIMW Index', 'UX1 Index', 'VXEEM Index', 'VXEFA Index', 'VXEWZ Index',
    'VXFXI Index', 'VXGDX Index', 'VXSLV Index', 'W 1 Comdty', 'W1DOW Index', 'WBI Index',
    'FNRETTM Index', 'FNREU Index', 'WIG Index', 'WIGCON Index', 'WIGFOOD Index', 'XU100 Index',
    'XUHIZ Index', 'XUMAL Index', 'XUSIN Index', 'XUTEK Index', 'YW1 Comdty', 'ZAREUR Curncy',
    'ZARJPY Curncy', 'ZARUSD Curncy'
]

df_for_xgb = pd.read_csv('Datasets/returns_all.csv')
df_for_xgb.drop(columns=[c for c in _cols_drop if c in df_for_xgb.columns], axis=1, inplace=True)

if 'all_tickers' not in globals():
    all_tickers = df_for_xgb.columns[1:].tolist()
if 'test_tickers' not in globals():
    test_tickers = ['GC1 Comdty', 'SI1 Comdty', 'HG1 Comdty']
if 'tickers_name' not in globals():
    tickers_name = 'all_tickers'

model_xgb = XGBRegressor(
    n_estimators=500,
    learning_rate=0.01,
    max_depth=4,
    min_child_weight=5,
    subsample=0.8,
    colsample_bytree=0.8,
    reg_alpha=0.0,
    reg_lambda=1.0,
    objective='reg:squarederror',
    random_state=42,
    n_jobs=-1,
)
model_name_xgb = 'XGB_n500_lr001_d4'
fonc_xgb = feature_engineering_rf

results_xgb = Parallel(n_jobs=-1)(
    delayed(process_one_ticker)(name, df_for_xgb, model_xgb, fonc_xgb, step_size=250, fold_size=1250) 
    for name in tqdm(all_tickers, desc="XGBoost — Parallel")
)

# --- 4. Nettoyage et Sauvegarde ---
# On retire les résultats None (ceux qui ont crashé)
results_xgb = [r for r in results_xgb if r is not None]

df_xgb_results = pd.DataFrame(results_xgb)
display(df_xgb_results)

# Sauvegarde sécurisée
os.makedirs('Resultats', exist_ok=True)
df_xgb_results.to_csv(f'Resultats/{"fenetre_5_ans"}/resultats_{tickers_name}_{model_name_xgb}.csv', index=False)

XGBoost — Parallel:  46%|████▌     | 472/1035 [04:35<05:09,  1.82it/s]/opt/anaconda3/lib/python3.12/site-packages/pandas/core/arraylike.py:399: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
XGBoost — Parallel: 100%|██████████| 1035/1035 [09:40<00:00,  1.78it/s]

AttributeError: 'NoneType' object has no attribute 'keys'

### Ridge + ElasticNet

Pipeline complète (préparation, entraînement sur `test_tickers`, export CSV), puis bloc optionnel pour `all_tickers`.

In [7]:
from sklearn.linear_model import Ridge, ElasticNet, Lasso
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

# Prérequis : imports (1), définition de `stats_forecasting` (2).
_cols_drop = [
    'KOCRD Index', 'NOBRON Index', 'CABROVER Index', 'EB03/3M Index', 'BZSTSETA Index',
    'MXNZ0EN Index', 'EGDIMW Index', 'UX1 Index', 'VXEEM Index', 'VXEFA Index', 'VXEWZ Index',
    'VXFXI Index', 'VXGDX Index', 'VXSLV Index', 'W 1 Comdty', 'W1DOW Index', 'WBI Index',
    'FNRETTM Index', 'FNREU Index', 'WIG Index', 'WIGCON Index', 'WIGFOOD Index', 'XU100 Index',
    'XUHIZ Index', 'XUMAL Index', 'XUSIN Index', 'XUTEK Index', 'YW1 Comdty', 'ZAREUR Curncy',
    'ZARJPY Curncy', 'ZARUSD Curncy'
]

df_for_linear = pd.read_csv('Datasets/returns_all.csv')
df_for_linear.drop(columns=[c for c in _cols_drop if c in df_for_linear.columns], axis=1, inplace=True)

if 'all_tickers' not in globals():
    all_tickers = df_for_linear.columns[1:].tolist()
if 'test_tickers' not in globals():
    test_tickers = ['GC1 Comdty', 'SI1 Comdty', 'HG1 Comdty']
if 'tickers_name' not in globals():
    tickers_name = 'all_tickers'

fonc_linear = feature_engineering_rf

# --- Ridge
model_ridge = make_pipeline(
    StandardScaler(),
    Ridge(alpha=0.01, random_state=42)
)
model_name_ridge = 'Ridge_alpha001_scaled'

results_ridge = []
for name in tqdm(all_tickers, desc='Ridge — all tickers'):
    try:
        res = stats_forecasting_DL(df_for_linear, name, model_ridge, fonc_linear, step_size=250, fold_size=1250, plot=False)
        results_ridge.append(res)
    except Exception as e:
        # print(f"Erreur sur {name} avec Ridge: {e}")
        continue

df_ridge_results = pd.DataFrame(results_ridge)
display(df_ridge_results)
df_ridge_results.to_csv(f'Resultats/{"fenetre_5_ans"}/resultats_{tickers_name}_{model_name_ridge}.csv', index=False)

# --- ElasticNet
model_enet = make_pipeline(
    StandardScaler(),
    ElasticNet(alpha=0.001, l1_ratio=0.2, max_iter=10000, random_state=42)
)
model_name_enet = 'ElasticNet_alpha1e3_l1r02_scaled'

results_enet = []
for name in tqdm(all_tickers, desc='ElasticNet — all tickers'):
    try:
        res = stats_forecasting_DL(df_for_linear, name, model_enet, fonc_linear, step_size = 250, fold_size = 1250, plot=False)
        results_enet.append(res)
    except Exception as e:
        # print(f"Erreur sur {name} avec ElasticNet: {e}")
        continue

df_enet_results = pd.DataFrame(results_enet)
display(df_enet_results)
df_enet_results.to_csv(f'Resultats/{"fenetre_5_ans"}/resultats_{tickers_name}_{model_name_enet}.csv', index=False)

# Pour lancer sur tous les actifs (long) :
# results_ridge_all = []
# for name in tqdm(all_tickers, desc='Ridge — tous les tickers'):
#     results_ridge_all.append(stats_forecasting(df_for_linear, name, model_ridge, fonc_linear, plot=False))
# pd.DataFrame(results_ridge_all).to_csv(f'Resultats/resultats_{tickers_name}_{model_name_ridge}.csv', index=False)

# results_enet_all = []
# for name in tqdm(all_tickers, desc='ElasticNet — tous les tickers'):
#     results_enet_all.append(stats_forecasting(df_for_linear, name, model_enet, fonc_linear, plot=False))
# pd.DataFrame(results_enet_all).to_csv(f'Resultats/resultats_{tickers_name}_{model_name_enet}.csv', index=False)

Ridge — all tickers:  45%|████▌     | 467/1035 [00:17<00:18, 30.99it/s]/opt/anaconda3/lib/python3.12/site-packages/pandas/core/arraylike.py:399: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
Ridge — all tickers: 100%|██████████| 1035/1035 [00:36<00:00, 27.99it/s]

,SYMBOL,MSE,OLS_R2,OLS_Intercept,OLS_Slope,OLS_P_Value_Intercept,P_Value_Slope
0,ADBF Index,0.000224,0.048931,0.000251,0.443373,0.473671,2.664818e-21
1,ADCM Index,0.000421,0.089775,0.001289,0.601083,0.012180,2.013065e-34
2,ADCT Index,0.000227,0.125868,0.000481,0.697932,0.157610,4.372662e-54
3,ADEG Index,0.000484,0.118314,0.000104,0.714822,0.850759,2.904764e-46
4,ADII Index,0.000058,0.065245,0.000175,0.464947,0.245447,8.646905e-36
...,...,...,...,...,...,...,...
993,USDDEM Curncy,0.000027,0.133947,-0.000116,0.696485,0.100052,1.771566e-170
994,USDEUR Curncy,0.000027,0.135236,-0.000108,0.685832,0.128094,7.831074e-171
995,USDJPY Curncy,0.000033,0.127799,-0.000184,0.726533,0.019174,5.896952e-162
996,FNMRC Index,0.001158,0.004970,0.000394,0.040366,0.226206,1.264274e-04
997,FNR5 Index,0.000512,0.026157,0.000226,0.179981,0.376597,2.176336e-31

ElasticNet — all tickers:  45%|████▌     | 469/1035 [00:19<00:16, 34.95it/s]/opt/anaconda3/lib/python3.12/site-packages/pandas/core/arraylike.py:399: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
ElasticNet — all tickers: 100%|██████████| 1035/1035 [00:42<00:00, 24.52it/s]

,SYMBOL,MSE,OLS_R2,OLS_Intercept,OLS_Slope,OLS_P_Value_Intercept,P_Value_Slope
0,ADBF Index,0.000212,0.053916,0.000154,0.602647,0.660390,2.304738e-23
1,ADCM Index,0.000407,0.095432,0.001170,0.719300,0.022456,1.366389e-36
2,ADCT Index,0.000210,0.135131,0.000404,0.889729,0.233626,3.167925e-58
3,ADEG Index,0.000478,0.116451,0.000169,0.788351,0.760245,1.618047e-45
4,ADII Index,0.000055,0.059559,0.000170,0.567317,0.260448,1.002240e-32
...,...,...,...,...,...,...,...
992,USDDEM Curncy,0.000027,0.112601,-0.000026,1.122138,0.713767,5.858976e-142
993,USDEUR Curncy,0.000027,0.115781,-0.000052,1.106750,0.470009,5.503155e-145
994,USDJPY Curncy,0.000033,0.106306,0.000003,1.090153,0.966401,1.755717e-133
995,FNMRC Index,0.000806,0.004737,0.000399,0.050636,0.222174,1.823555e-04
996,FNR5 Index,0.000395,0.032200,0.000232,0.286266,0.364178,2.326999e-38

### OLS + LASSO

In [8]:
from sklearn.linear_model import LinearRegression, Lasso
# (Les autres imports restent identiques)

# --- OLS (Ordinary Least Squares)
# La régression linéaire classique n'a pas de paramètre de régularisation (alpha)
model_ols = make_pipeline(
    StandardScaler(),
    LinearRegression() 
)
model_name_ols = 'OLS_scaled'

results_ols = []
for name in tqdm(all_tickers, desc='OLS — all tickers'):
    try:        
        res = stats_forecasting_DL(df_for_linear, name, model_ols, fonc_linear, step_size=250, fold_size=1250, plot=False)
        results_ols.append(res)
    except Exception as e:
        # print(f"Erreur sur {name} avec OLS: {e}")
        continue

df_ols_results = pd.DataFrame(results_ols)
display(df_ols_results)
df_ols_results.to_csv(f'Resultats/{"fenetre_5_ans"}/resultats_{tickers_name}_{model_name_ols}.csv', index=False)


# --- LASSO
# Le Lasso utilise une pénalité L1. J'ai mis un alpha de 0.001 et augmenté max_iter
# pour éviter les problèmes de convergence, comme pour ton ElasticNet.
model_lasso = make_pipeline(
    StandardScaler(),
    Lasso(alpha=0.001, max_iter=10000, random_state=42)
)
model_name_lasso = 'Lasso_alpha1e3_scaled'

results_lasso = []
for name in tqdm(all_tickers, desc='LASSO — all tickers'):
    try:
        res = stats_forecasting_DL(df_for_linear, name, model_lasso, fonc_linear, step_size=250, fold_size=1250, plot=False)
        results_lasso.append(res)
    except Exception as e:
        # print(f"Erreur sur {name} avec LASSO: {e}")
        continue

df_lasso_results = pd.DataFrame(results_lasso)
display(df_lasso_results)
df_lasso_results.to_csv(f'Resultats/{"fenetre_5_ans"}/resultats_{tickers_name}_{model_name_lasso}.csv', index=False)

OLS — all tickers:  45%|████▌     | 466/1035 [00:17<00:16, 33.61it/s]/opt/anaconda3/lib/python3.12/site-packages/pandas/core/arraylike.py:399: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
OLS — all tickers: 100%|██████████| 1035/1035 [00:38<00:00, 26.55it/s]

,SYMBOL,MSE,OLS_R2,OLS_Intercept,OLS_Slope,OLS_P_Value_Intercept,P_Value_Slope
0,ADBF Index,0.000224,0.048931,0.000251,0.443356,0.473642,2.666139e-21
1,ADCM Index,0.000421,0.089774,0.001289,0.601059,0.012178,2.015050e-34
2,ADCT Index,0.000227,0.125867,0.000481,0.697909,0.157607,4.373741e-54
3,ADEG Index,0.000484,0.118314,0.000104,0.714803,0.850757,2.903683e-46
4,ADII Index,0.000058,0.065244,0.000175,0.464933,0.245455,8.648128e-36
...,...,...,...,...,...,...,...
993,USDDEM Curncy,0.000027,0.133946,-0.000116,0.696455,0.100063,1.775069e-170
994,USDEUR Curncy,0.000027,0.135235,-0.000108,0.685801,0.128113,7.849511e-171
995,USDJPY Curncy,0.000033,0.127800,-0.000184,0.726508,0.019171,5.888189e-162
996,FNMRC Index,0.001158,0.004970,0.000394,0.040361,0.226202,1.264229e-04
997,FNR5 Index,0.000512,0.026154,0.000226,0.179953,0.376638,2.193618e-31

LASSO — all tickers:  45%|████▌     | 469/1035 [00:17<00:16, 34.26it/s]/opt/anaconda3/lib/python3.12/site-packages/pandas/core/arraylike.py:399: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
LASSO — all tickers: 100%|██████████| 1035/1035 [00:39<00:00, 26.51it/s]

,SYMBOL,MSE,OLS_R2,OLS_Intercept,OLS_Slope,OLS_P_Value_Intercept,P_Value_Slope
0,ADBF Index,0.000208,0.059893,-0.000320,1.498669,0.372513,7.526287e-26
1,ADCM Index,0.000397,0.106681,0.000365,1.196409,0.477055,6.105236e-41
2,ADCT Index,0.000211,0.090047,0.000138,1.270712,0.692917,1.829152e-38
3,ADEG Index,0.000484,0.095522,0.000066,1.095121,0.906490,3.068292e-37
4,ADII Index,0.000054,0.042324,0.000121,1.010817,0.425081,1.552270e-23
...,...,...,...,...,...,...,...
992,USDDEM Curncy,0.000029,0.046886,0.000011,2.321304,0.882902,3.352755e-58
993,USDEUR Curncy,0.000029,0.047747,0.000005,2.290294,0.941897,8.590485e-59
994,USDJPY Curncy,0.000036,0.052138,-0.000034,2.331598,0.675049,1.355723e-64
995,FNMRC Index,0.000308,0.010355,0.000387,0.250862,0.221757,3.010142e-08
996,FNR5 Index,0.000330,0.028646,-0.000034,0.748345,0.894053,2.959325e-34

In [9]:
import pandas as pd
from tqdm import tqdm
from sklearn.model_selection import GridSearchCV, TimeSeriesSplit
from xgboost import XGBRegressor
from sklearn.linear_model import Ridge, ElasticNet 

# 1. Définition du découpage temporel et des grilles
tscv = TimeSeriesSplit(n_splits=3) 

# XGBoost
grid_xgb = GridSearchCV(
    estimator=XGBRegressor(objective='reg:squarederror', random_state=42, n_jobs=1),
    param_grid={'n_estimators': [100, 300, 500], 'learning_rate': [0.01, 0.03, 0.1], 'max_depth': [3, 4, 6]},
    cv=tscv, scoring='neg_mean_squared_error', n_jobs=-1
)

# Ridge
grid_ridge = GridSearchCV(
    estimator=Ridge(random_state=42),
    param_grid={'alpha': [0.001, 0.01, 0.1, 1.0, 10.0]},
    cv=tscv, scoring='neg_mean_squared_error', n_jobs=-1
)

# ElasticNet
grid_en = GridSearchCV(
    estimator=ElasticNet(random_state=42, max_iter=5000),
    param_grid={'alpha': [0.1, 1.0, 10.0, 100.0], 'l1_ratio': [0.2, 0.5, 0.8]},
    cv=tscv, scoring='neg_mean_squared_error', n_jobs=-1
)

# 2. Boucle pour chercher les meilleurs paramètres
liste_meilleurs_params = []

for name in tqdm(test_tickers, desc='Recherche des meilleurs paramètres'):
    
    # Préparation des données pour le ticker courant
    df_ticker = extract(df_for_xgb, name)
    df_ticker["Close"] = Close_price(df_ticker)
    df_ticker["log_return"] = log_return(df_ticker)
    df_ticker = fonc_xgb(df_ticker)
    df_ticker = df_ticker.dropna()
    
    # Séparation X et y
    X = df_ticker.drop(columns=['return', 'log_return', 'Close'], errors='ignore')
    y = df_ticker['log_return']
    
    # Entraînement des grilles pour trouver les meilleurs paramètres
    grid_xgb.fit(X, y)
    grid_ridge.fit(X, y)
    grid_en.fit(X, y)
    
    # Stockage dans la liste
    liste_meilleurs_params.append({
        'Ticker': name,
        'XGBoost_Params': grid_xgb.best_params_,
        'Ridge_Params': grid_ridge.best_params_,
        'ElasticNet_Params': grid_en.best_params_
    })

# 3. Création et affichage du tableau final
df_meilleurs_params = pd.DataFrame(liste_meilleurs_params)

print("\n=== TABLEAU DES MEILLEURS PARAMÈTRES ===")
display(df_meilleurs_params)

# Optionnel : Sauvegarder le tableau en CSV
# df_meilleurs_params.to_csv("meilleurs_parametres_modeles.csv", index=False)

Recherche des meilleurs paramètres:   0%|          | 0/9 [00:00<?, ?it/s]

NameError: name 'df_for_xgb' is not defined

In [ ]:
df_meilleurs_params.to_csv("meilleurs_parametres_modeles.csv", index=False)