## LightGBM hyperparameter search on representative tickers

This notebook searches for robust LightGBM hyperparameters on a small set of representative `test_tickers`, using the existing walk-forward cross-validation (`WFCV`) pipeline.

In [2]:
import numpy as np
import pandas as pd
import statsmodels.api as sm

from sklearn.metrics import mean_squared_error
from sklearn.model_selection import ParameterGrid

try:
    from lightgbm import LGBMRegressor
except ImportError as e:
    raise ImportError(
        "lightgbm n'est pas installe. Installe-le avec `pip install lightgbm` puis relance."
    ) from e

from utils import extract, Close_price, log_return, feature_engineering_rf, WFCV


COLS_TO_DROP = [
    'KOCRD Index', 'NOBRON Index', 'CABROVER Index', 'EB03/3M Index', 'BZSTSETA Index',
    'MXNZ0EN Index', 'EGDIMW Index', 'UX1 Index', 'VXEEM Index', 'VXEFA Index', 'VXEWZ Index',
    'VXFXI Index', 'VXGDX Index', 'VXSLV Index', 'W 1 Comdty', 'W1DOW Index', 'WBI Index',
    'FNRETTM Index', 'FNREU Index', 'WIG Index', 'WIGCON Index', 'WIGFOOD Index', 'XU100 Index',
    'XUHIZ Index', 'XUMAL Index', 'XUSIN Index', 'XUTEK Index', 'YW1 Comdty', 'ZAREUR Curncy',
    'ZARJPY Curncy', 'ZARUSD Curncy'
]

TEST_TICKERS = [
    'GC1 Comdty',
    'BLQ2TRUU Index',
    'GBPJPY Curncy',
    'M4EUHDVD Index',
    'HFRXM Index',
    'GB1M Index',
    'QW2I Index',
    'FNER Index',
    'SPX Index',
]

df = pd.read_csv('Datasets/returns_all.csv')
df.drop(columns=[c for c in COLS_TO_DROP if c in df.columns], inplace=True)
all_tickers = df.columns[1:].tolist()
tickers_name = 'all_tickers'

print(f'{len(all_tickers)} tickers disponibles apres filtrage.')
print('Test tickers:', TEST_TICKERS)

1035 tickers disponibles apres filtrage.
Test tickers: ['GC1 Comdty', 'BLQ2TRUU Index', 'GBPJPY Curncy', 'M4EUHDVD Index', 'HFRXM Index', 'GB1M Index', 'QW2I Index', 'FNER Index', 'SPX Index']

In [3]:
def make_lgbm_model(params):
    base_params = {
        'objective': 'regression',
        'random_state': 42,
        'n_jobs': -1,
        'verbosity': -1,
    }
    base_params.update(params)
    return LGBMRegressor(**base_params)


def stats_forecasting_lgbm(df_all, name_ticker, model_params, feature_engineering=feature_engineering_rf, step_size=50, fold_size=200):
    df_ticker = extract(df_all, name_ticker)
    df_ticker['Close'] = Close_price(df_ticker)
    df_ticker['log_return'] = log_return(df_ticker)
    df_ticker = feature_engineering(df_ticker)

    X = df_ticker.drop(columns=['return', 'log_return', 'Close'])
    y = df_ticker['log_return']

    model = make_lgbm_model(model_params)
    y_pred, y_truth, mse_tab, r2 = WFCV(X, y, model, step_size=step_size, fold_size=fold_size)
    reg = sm.OLS(y_truth, sm.add_constant(y_pred)).fit()

    return {
        'SYMBOL': name_ticker,
        'MSE': float(np.mean(mse_tab)) if len(mse_tab) else np.nan,
        'OLS_R2': float(reg.rsquared),
        'OLS_Intercept': float(reg.params[0]),
        'OLS_Slope': float(reg.params[1]),
        'OLS_P_Value_Intercept': float(reg.pvalues[0]),
        'P_Value_Slope': float(reg.pvalues[1]),
        'n_samples': int(len(df_ticker)),
    }


def evaluate_lgbm_config(df_all, tickers, model_params, feature_engineering=feature_engineering_rf, step_size=50, fold_size=200):
    per_ticker_results = []
    for ticker in tickers:
        result = stats_forecasting_lgbm(
            df_all=df_all,
            name_ticker=ticker,
            model_params=model_params,
            feature_engineering=feature_engineering,
            step_size=step_size,
            fold_size=fold_size,
        )
        per_ticker_results.append(result)

    df_results = pd.DataFrame(per_ticker_results)

    summary = {
        'mean_mse': float(df_results['MSE'].mean()),
        'median_mse': float(df_results['MSE'].median()),
        'std_mse': float(df_results['MSE'].std()),
        'mean_ols_r2': float(df_results['OLS_R2'].mean()),
        'median_ols_r2': float(df_results['OLS_R2'].median()),
        'n_tickers': int(len(df_results)),
    }

    return df_results, summary


def search_lgbm_hyperparams(df_all, tickers, param_grid, feature_engineering=feature_engineering_rf, step_size=50, fold_size=200):
    search_rows = []
    per_config_results = {}

    for i, params in enumerate(ParameterGrid(param_grid), start=1):
        df_results, summary = evaluate_lgbm_config(
            df_all=df_all,
            tickers=tickers,
            model_params=params,
            feature_engineering=feature_engineering,
            step_size=step_size,
            fold_size=fold_size,
        )

        row = {'config_id': i}
        row.update(params)
        row.update(summary)
        search_rows.append(row)
        per_config_results[i] = {
            'params': params,
            'per_ticker_results': df_results,
            'summary': summary,
        }

        print(f"Config {i}: mean_mse={summary['mean_mse']:.6f} | mean_ols_r2={summary['mean_ols_r2']:.4f} | params={params}")

    search_df = pd.DataFrame(search_rows).sort_values(['mean_mse', 'median_mse']).reset_index(drop=True)
    return search_df, per_config_results

In [3]:
# Starter grid for a first-pass search.
# You can widen or narrow it depending on runtime.
param_grid = {
    'n_estimators': [200, 500],
    'learning_rate': [0.02, 0.05],
    'num_leaves': [15, 31, 63],
    'max_depth': [-1, 5, 8],
    'min_child_samples': [20, 50],
    'subsample': [0.8],
    'colsample_bytree': [0.8],
    'reg_alpha': [0.0, 0.1],
    'reg_lambda': [1.0, 3.0],
}

STEP_SIZE = 50
FOLD_SIZE = 200

search_df, per_config_results = search_lgbm_hyperparams(
    df_all=df,
    tickers=TEST_TICKERS,
    param_grid=param_grid,
    feature_engineering=feature_engineering_rf,
    step_size=STEP_SIZE,
    fold_size=FOLD_SIZE,
)

display(search_df.head(10))

# Best configuration and detailed per-ticker scores
best_config_id = int(search_df.iloc[0]['config_id'])
best_params = per_config_results[best_config_id]['params']
best_per_ticker = per_config_results[best_config_id]['per_ticker_results']

print('Best config id:', best_config_id)
print('Best params:', best_params)
display(best_per_ticker)

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 1: mean_mse=0.000293 | mean_ols_r2=0.0502 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 2: mean_mse=0.000292 | mean_ols_r2=0.0503 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 3: mean_mse=0.000291 | mean_ols_r2=0.0235 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 4: mean_mse=0.000289 | mean_ols_r2=0.0235 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 5: mean_mse=0.000293 | mean_ols_r2=0.0502 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 6: mean_mse=0.000292 | mean_ols_r2=0.0503 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 7: mean_mse=0.000291 | mean_ols_r2=0.0235 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 8: mean_mse=0.000289 | mean_ols_r2=0.0235 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 9: mean_mse=0.000293 | mean_ols_r2=0.0502 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 10: mean_mse=0.000292 | mean_ols_r2=0.0503 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 11: mean_mse=0.000291 | mean_ols_r2=0.0235 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 12: mean_mse=0.000289 | mean_ols_r2=0.0235 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 13: mean_mse=0.000323 | mean_ols_r2=0.0492 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 14: mean_mse=0.000322 | mean_ols_r2=0.0498 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 15: mean_mse=0.000314 | mean_ols_r2=0.0229 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 16: mean_mse=0.000308 | mean_ols_r2=0.0235 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 17: mean_mse=0.000323 | mean_ols_r2=0.0492 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 18: mean_mse=0.000322 | mean_ols_r2=0.0498 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 19: mean_mse=0.000314 | mean_ols_r2=0.0229 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 20: mean_mse=0.000308 | mean_ols_r2=0.0235 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 21: mean_mse=0.000323 | mean_ols_r2=0.0492 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 22: mean_mse=0.000322 | mean_ols_r2=0.0498 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 23: mean_mse=0.000314 | mean_ols_r2=0.0229 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 24: mean_mse=0.000308 | mean_ols_r2=0.0235 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 25: mean_mse=0.000280 | mean_ols_r2=0.0414 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 26: mean_mse=0.000280 | mean_ols_r2=0.0410 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 27: mean_mse=0.000280 | mean_ols_r2=0.0214 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 28: mean_mse=0.000280 | mean_ols_r2=0.0213 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 29: mean_mse=0.000280 | mean_ols_r2=0.0414 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 30: mean_mse=0.000280 | mean_ols_r2=0.0410 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 31: mean_mse=0.000280 | mean_ols_r2=0.0214 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 32: mean_mse=0.000280 | mean_ols_r2=0.0213 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 33: mean_mse=0.000280 | mean_ols_r2=0.0414 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 34: mean_mse=0.000280 | mean_ols_r2=0.0410 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 35: mean_mse=0.000280 | mean_ols_r2=0.0214 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 36: mean_mse=0.000280 | mean_ols_r2=0.0213 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 37: mean_mse=0.000294 | mean_ols_r2=0.0449 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 38: mean_mse=0.000294 | mean_ols_r2=0.0448 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 39: mean_mse=0.000293 | mean_ols_r2=0.0225 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 40: mean_mse=0.000292 | mean_ols_r2=0.0225 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 41: mean_mse=0.000294 | mean_ols_r2=0.0449 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 42: mean_mse=0.000294 | mean_ols_r2=0.0448 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 43: mean_mse=0.000293 | mean_ols_r2=0.0225 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 44: mean_mse=0.000292 | mean_ols_r2=0.0225 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 45: mean_mse=0.000294 | mean_ols_r2=0.0449 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 46: mean_mse=0.000294 | mean_ols_r2=0.0448 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 47: mean_mse=0.000293 | mean_ols_r2=0.0225 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 48: mean_mse=0.000292 | mean_ols_r2=0.0225 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 49: mean_mse=0.000294 | mean_ols_r2=0.0504 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 50: mean_mse=0.000291 | mean_ols_r2=0.0506 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 51: mean_mse=0.000290 | mean_ols_r2=0.0240 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 52: mean_mse=0.000289 | mean_ols_r2=0.0236 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 53: mean_mse=0.000294 | mean_ols_r2=0.0504 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 54: mean_mse=0.000291 | mean_ols_r2=0.0506 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 55: mean_mse=0.000290 | mean_ols_r2=0.0240 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 56: mean_mse=0.000289 | mean_ols_r2=0.0236 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 57: mean_mse=0.000294 | mean_ols_r2=0.0504 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 58: mean_mse=0.000291 | mean_ols_r2=0.0506 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 59: mean_mse=0.000290 | mean_ols_r2=0.0240 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 60: mean_mse=0.000289 | mean_ols_r2=0.0236 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 61: mean_mse=0.000323 | mean_ols_r2=0.0497 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 62: mean_mse=0.000319 | mean_ols_r2=0.0501 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 63: mean_mse=0.000313 | mean_ols_r2=0.0235 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 64: mean_mse=0.000310 | mean_ols_r2=0.0235 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 65: mean_mse=0.000323 | mean_ols_r2=0.0497 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 66: mean_mse=0.000319 | mean_ols_r2=0.0501 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 67: mean_mse=0.000313 | mean_ols_r2=0.0235 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 68: mean_mse=0.000310 | mean_ols_r2=0.0235 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 69: mean_mse=0.000323 | mean_ols_r2=0.0497 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 70: mean_mse=0.000319 | mean_ols_r2=0.0501 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 71: mean_mse=0.000313 | mean_ols_r2=0.0235 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 72: mean_mse=0.000310 | mean_ols_r2=0.0235 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 73: mean_mse=0.000280 | mean_ols_r2=0.0414 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 74: mean_mse=0.000280 | mean_ols_r2=0.0410 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 75: mean_mse=0.000280 | mean_ols_r2=0.0214 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 76: mean_mse=0.000280 | mean_ols_r2=0.0213 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 77: mean_mse=0.000280 | mean_ols_r2=0.0414 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 78: mean_mse=0.000280 | mean_ols_r2=0.0410 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 79: mean_mse=0.000280 | mean_ols_r2=0.0214 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 80: mean_mse=0.000280 | mean_ols_r2=0.0213 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 81: mean_mse=0.000280 | mean_ols_r2=0.0414 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 82: mean_mse=0.000280 | mean_ols_r2=0.0410 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 83: mean_mse=0.000280 | mean_ols_r2=0.0214 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 84: mean_mse=0.000280 | mean_ols_r2=0.0213 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 85: mean_mse=0.000294 | mean_ols_r2=0.0449 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 86: mean_mse=0.000294 | mean_ols_r2=0.0448 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 87: mean_mse=0.000293 | mean_ols_r2=0.0225 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 88: mean_mse=0.000292 | mean_ols_r2=0.0225 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 89: mean_mse=0.000294 | mean_ols_r2=0.0449 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 90: mean_mse=0.000294 | mean_ols_r2=0.0448 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 91: mean_mse=0.000293 | mean_ols_r2=0.0225 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 92: mean_mse=0.000292 | mean_ols_r2=0.0225 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 93: mean_mse=0.000294 | mean_ols_r2=0.0449 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 94: mean_mse=0.000294 | mean_ols_r2=0.0448 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 95: mean_mse=0.000293 | mean_ols_r2=0.0225 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 96: mean_mse=0.000292 | mean_ols_r2=0.0225 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 97: mean_mse=0.000293 | mean_ols_r2=0.0502 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 98: mean_mse=0.000292 | mean_ols_r2=0.0503 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 99: mean_mse=0.000291 | mean_ols_r2=0.0235 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 100: mean_mse=0.000289 | mean_ols_r2=0.0235 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 101: mean_mse=0.000293 | mean_ols_r2=0.0502 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 102: mean_mse=0.000292 | mean_ols_r2=0.0503 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 103: mean_mse=0.000291 | mean_ols_r2=0.0235 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 104: mean_mse=0.000289 | mean_ols_r2=0.0235 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 105: mean_mse=0.000293 | mean_ols_r2=0.0502 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 106: mean_mse=0.000292 | mean_ols_r2=0.0503 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 107: mean_mse=0.000291 | mean_ols_r2=0.0235 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 108: mean_mse=0.000289 | mean_ols_r2=0.0235 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 109: mean_mse=0.000323 | mean_ols_r2=0.0492 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 110: mean_mse=0.000322 | mean_ols_r2=0.0498 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 111: mean_mse=0.000314 | mean_ols_r2=0.0229 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 112: mean_mse=0.000308 | mean_ols_r2=0.0235 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 113: mean_mse=0.000323 | mean_ols_r2=0.0492 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 114: mean_mse=0.000322 | mean_ols_r2=0.0498 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 115: mean_mse=0.000314 | mean_ols_r2=0.0229 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 116: mean_mse=0.000308 | mean_ols_r2=0.0235 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 117: mean_mse=0.000323 | mean_ols_r2=0.0492 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 118: mean_mse=0.000322 | mean_ols_r2=0.0498 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 119: mean_mse=0.000314 | mean_ols_r2=0.0229 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 120: mean_mse=0.000308 | mean_ols_r2=0.0235 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 121: mean_mse=0.000280 | mean_ols_r2=0.0414 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 122: mean_mse=0.000280 | mean_ols_r2=0.0410 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 123: mean_mse=0.000280 | mean_ols_r2=0.0214 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 124: mean_mse=0.000280 | mean_ols_r2=0.0213 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 125: mean_mse=0.000280 | mean_ols_r2=0.0414 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 126: mean_mse=0.000280 | mean_ols_r2=0.0410 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 127: mean_mse=0.000280 | mean_ols_r2=0.0214 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 128: mean_mse=0.000280 | mean_ols_r2=0.0213 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 129: mean_mse=0.000280 | mean_ols_r2=0.0414 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 130: mean_mse=0.000280 | mean_ols_r2=0.0410 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 131: mean_mse=0.000280 | mean_ols_r2=0.0214 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 132: mean_mse=0.000280 | mean_ols_r2=0.0213 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 133: mean_mse=0.000294 | mean_ols_r2=0.0449 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 134: mean_mse=0.000294 | mean_ols_r2=0.0448 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 135: mean_mse=0.000293 | mean_ols_r2=0.0225 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 136: mean_mse=0.000292 | mean_ols_r2=0.0225 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 137: mean_mse=0.000294 | mean_ols_r2=0.0449 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 138: mean_mse=0.000294 | mean_ols_r2=0.0448 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 139: mean_mse=0.000293 | mean_ols_r2=0.0225 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 140: mean_mse=0.000292 | mean_ols_r2=0.0225 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 141: mean_mse=0.000294 | mean_ols_r2=0.0449 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 142: mean_mse=0.000294 | mean_ols_r2=0.0448 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 143: mean_mse=0.000293 | mean_ols_r2=0.0225 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 144: mean_mse=0.000292 | mean_ols_r2=0.0225 | params={'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 145: mean_mse=0.000324 | mean_ols_r2=0.0492 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 146: mean_mse=0.000315 | mean_ols_r2=0.0494 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 147: mean_mse=0.000313 | mean_ols_r2=0.0231 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 148: mean_mse=0.000312 | mean_ols_r2=0.0234 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 149: mean_mse=0.000324 | mean_ols_r2=0.0492 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 150: mean_mse=0.000315 | mean_ols_r2=0.0494 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 151: mean_mse=0.000313 | mean_ols_r2=0.0231 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 152: mean_mse=0.000312 | mean_ols_r2=0.0234 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 153: mean_mse=0.000324 | mean_ols_r2=0.0492 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 154: mean_mse=0.000315 | mean_ols_r2=0.0494 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 155: mean_mse=0.000313 | mean_ols_r2=0.0231 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 156: mean_mse=0.000312 | mean_ols_r2=0.0234 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 157: mean_mse=0.000353 | mean_ols_r2=0.0464 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 158: mean_mse=0.000346 | mean_ols_r2=0.0467 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 159: mean_mse=0.000337 | mean_ols_r2=0.0217 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 160: mean_mse=0.000337 | mean_ols_r2=0.0223 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 161: mean_mse=0.000353 | mean_ols_r2=0.0464 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 162: mean_mse=0.000346 | mean_ols_r2=0.0467 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 163: mean_mse=0.000337 | mean_ols_r2=0.0217 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 164: mean_mse=0.000337 | mean_ols_r2=0.0223 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 165: mean_mse=0.000353 | mean_ols_r2=0.0464 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 166: mean_mse=0.000346 | mean_ols_r2=0.0467 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 167: mean_mse=0.000337 | mean_ols_r2=0.0217 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 168: mean_mse=0.000337 | mean_ols_r2=0.0223 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 169: mean_mse=0.000295 | mean_ols_r2=0.0447 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 170: mean_mse=0.000295 | mean_ols_r2=0.0446 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 171: mean_mse=0.000293 | mean_ols_r2=0.0225 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 172: mean_mse=0.000292 | mean_ols_r2=0.0225 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 173: mean_mse=0.000295 | mean_ols_r2=0.0447 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 174: mean_mse=0.000295 | mean_ols_r2=0.0446 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 175: mean_mse=0.000293 | mean_ols_r2=0.0225 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 176: mean_mse=0.000292 | mean_ols_r2=0.0225 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 177: mean_mse=0.000295 | mean_ols_r2=0.0447 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 178: mean_mse=0.000295 | mean_ols_r2=0.0446 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 179: mean_mse=0.000293 | mean_ols_r2=0.0225 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 180: mean_mse=0.000292 | mean_ols_r2=0.0225 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 181: mean_mse=0.000329 | mean_ols_r2=0.0439 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 182: mean_mse=0.000329 | mean_ols_r2=0.0438 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 183: mean_mse=0.000321 | mean_ols_r2=0.0224 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 184: mean_mse=0.000318 | mean_ols_r2=0.0224 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 185: mean_mse=0.000329 | mean_ols_r2=0.0439 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 186: mean_mse=0.000329 | mean_ols_r2=0.0438 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 187: mean_mse=0.000321 | mean_ols_r2=0.0224 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 188: mean_mse=0.000318 | mean_ols_r2=0.0224 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 189: mean_mse=0.000329 | mean_ols_r2=0.0439 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 190: mean_mse=0.000329 | mean_ols_r2=0.0438 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 191: mean_mse=0.000321 | mean_ols_r2=0.0224 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 192: mean_mse=0.000318 | mean_ols_r2=0.0224 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 193: mean_mse=0.000324 | mean_ols_r2=0.0496 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 194: mean_mse=0.000319 | mean_ols_r2=0.0500 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 195: mean_mse=0.000317 | mean_ols_r2=0.0230 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 196: mean_mse=0.000313 | mean_ols_r2=0.0233 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 197: mean_mse=0.000324 | mean_ols_r2=0.0496 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 198: mean_mse=0.000319 | mean_ols_r2=0.0500 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 199: mean_mse=0.000317 | mean_ols_r2=0.0230 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 200: mean_mse=0.000313 | mean_ols_r2=0.0233 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 201: mean_mse=0.000324 | mean_ols_r2=0.0496 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 202: mean_mse=0.000319 | mean_ols_r2=0.0500 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 203: mean_mse=0.000317 | mean_ols_r2=0.0230 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 204: mean_mse=0.000313 | mean_ols_r2=0.0233 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 205: mean_mse=0.000354 | mean_ols_r2=0.0470 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 206: mean_mse=0.000348 | mean_ols_r2=0.0473 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 207: mean_mse=0.000340 | mean_ols_r2=0.0218 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 208: mean_mse=0.000340 | mean_ols_r2=0.0220 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 209: mean_mse=0.000354 | mean_ols_r2=0.0470 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 210: mean_mse=0.000348 | mean_ols_r2=0.0473 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 211: mean_mse=0.000340 | mean_ols_r2=0.0218 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 212: mean_mse=0.000340 | mean_ols_r2=0.0220 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 213: mean_mse=0.000354 | mean_ols_r2=0.0470 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 214: mean_mse=0.000348 | mean_ols_r2=0.0473 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 215: mean_mse=0.000340 | mean_ols_r2=0.0218 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 216: mean_mse=0.000340 | mean_ols_r2=0.0220 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 217: mean_mse=0.000295 | mean_ols_r2=0.0447 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 218: mean_mse=0.000295 | mean_ols_r2=0.0446 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 219: mean_mse=0.000293 | mean_ols_r2=0.0225 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 220: mean_mse=0.000292 | mean_ols_r2=0.0225 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 221: mean_mse=0.000295 | mean_ols_r2=0.0447 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 222: mean_mse=0.000295 | mean_ols_r2=0.0446 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 223: mean_mse=0.000293 | mean_ols_r2=0.0225 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 224: mean_mse=0.000292 | mean_ols_r2=0.0225 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 225: mean_mse=0.000295 | mean_ols_r2=0.0447 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 226: mean_mse=0.000295 | mean_ols_r2=0.0446 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 227: mean_mse=0.000293 | mean_ols_r2=0.0225 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 228: mean_mse=0.000292 | mean_ols_r2=0.0225 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 229: mean_mse=0.000329 | mean_ols_r2=0.0439 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 230: mean_mse=0.000329 | mean_ols_r2=0.0438 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 231: mean_mse=0.000321 | mean_ols_r2=0.0224 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 232: mean_mse=0.000318 | mean_ols_r2=0.0224 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 233: mean_mse=0.000329 | mean_ols_r2=0.0439 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 234: mean_mse=0.000329 | mean_ols_r2=0.0438 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 235: mean_mse=0.000321 | mean_ols_r2=0.0224 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 236: mean_mse=0.000318 | mean_ols_r2=0.0224 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 237: mean_mse=0.000329 | mean_ols_r2=0.0439 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 238: mean_mse=0.000329 | mean_ols_r2=0.0438 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 239: mean_mse=0.000321 | mean_ols_r2=0.0224 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 240: mean_mse=0.000318 | mean_ols_r2=0.0224 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 241: mean_mse=0.000324 | mean_ols_r2=0.0492 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 242: mean_mse=0.000315 | mean_ols_r2=0.0494 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 243: mean_mse=0.000313 | mean_ols_r2=0.0231 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 244: mean_mse=0.000312 | mean_ols_r2=0.0234 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 245: mean_mse=0.000324 | mean_ols_r2=0.0492 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 246: mean_mse=0.000315 | mean_ols_r2=0.0494 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 247: mean_mse=0.000313 | mean_ols_r2=0.0231 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 248: mean_mse=0.000312 | mean_ols_r2=0.0234 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 249: mean_mse=0.000324 | mean_ols_r2=0.0492 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 250: mean_mse=0.000315 | mean_ols_r2=0.0494 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 251: mean_mse=0.000313 | mean_ols_r2=0.0231 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 252: mean_mse=0.000312 | mean_ols_r2=0.0234 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 253: mean_mse=0.000353 | mean_ols_r2=0.0464 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 254: mean_mse=0.000346 | mean_ols_r2=0.0467 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 255: mean_mse=0.000337 | mean_ols_r2=0.0217 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 256: mean_mse=0.000337 | mean_ols_r2=0.0223 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 257: mean_mse=0.000353 | mean_ols_r2=0.0464 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 258: mean_mse=0.000346 | mean_ols_r2=0.0467 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 259: mean_mse=0.000337 | mean_ols_r2=0.0217 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 260: mean_mse=0.000337 | mean_ols_r2=0.0223 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 261: mean_mse=0.000353 | mean_ols_r2=0.0464 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 262: mean_mse=0.000346 | mean_ols_r2=0.0467 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 263: mean_mse=0.000337 | mean_ols_r2=0.0217 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 264: mean_mse=0.000337 | mean_ols_r2=0.0223 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 20, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 265: mean_mse=0.000295 | mean_ols_r2=0.0447 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 266: mean_mse=0.000295 | mean_ols_r2=0.0446 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 267: mean_mse=0.000293 | mean_ols_r2=0.0225 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 268: mean_mse=0.000292 | mean_ols_r2=0.0225 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 269: mean_mse=0.000295 | mean_ols_r2=0.0447 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 270: mean_mse=0.000295 | mean_ols_r2=0.0446 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 271: mean_mse=0.000293 | mean_ols_r2=0.0225 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 272: mean_mse=0.000292 | mean_ols_r2=0.0225 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 273: mean_mse=0.000295 | mean_ols_r2=0.0447 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 274: mean_mse=0.000295 | mean_ols_r2=0.0446 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 275: mean_mse=0.000293 | mean_ols_r2=0.0225 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 276: mean_mse=0.000292 | mean_ols_r2=0.0225 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 277: mean_mse=0.000329 | mean_ols_r2=0.0439 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 278: mean_mse=0.000329 | mean_ols_r2=0.0438 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 279: mean_mse=0.000321 | mean_ols_r2=0.0224 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 280: mean_mse=0.000318 | mean_ols_r2=0.0224 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 281: mean_mse=0.000329 | mean_ols_r2=0.0439 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 282: mean_mse=0.000329 | mean_ols_r2=0.0438 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 283: mean_mse=0.000321 | mean_ols_r2=0.0224 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 284: mean_mse=0.000318 | mean_ols_r2=0.0224 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 31, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 285: mean_mse=0.000329 | mean_ols_r2=0.0439 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 286: mean_mse=0.000329 | mean_ols_r2=0.0438 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.0, 'reg_lambda': 3.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 287: mean_mse=0.000321 | mean_ols_r2=0.0224 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.8}

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Config 288: mean_mse=0.000318 | mean_ols_r2=0.0224 | params={'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_samples': 50, 'n_estimators': 500, 'num_leaves': 63, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

,config_id,colsample_bytree,learning_rate,max_depth,min_child_samples,n_estimators,num_leaves,reg_alpha,reg_lambda,subsample,mean_mse,median_mse,std_mse,mean_ols_r2,median_ols_r2,n_tickers
0,28,0.8,0.02,-1,50,200,15,0.1,3.0,0.8,0.00028,0.000121,0.000537,0.021322,0.014763,9
1,32,0.8,0.02,-1,50,200,31,0.1,3.0,0.8,0.00028,0.000121,0.000537,0.021322,0.014763,9
2,36,0.8,0.02,-1,50,200,63,0.1,3.0,0.8,0.00028,0.000121,0.000537,0.021322,0.014763,9
3,76,0.8,0.02,5,50,200,15,0.1,3.0,0.8,0.00028,0.000121,0.000537,0.021322,0.014763,9
4,80,0.8,0.02,5,50,200,31,0.1,3.0,0.8,0.00028,0.000121,0.000537,0.021322,0.014763,9
5,84,0.8,0.02,5,50,200,63,0.1,3.0,0.8,0.00028,0.000121,0.000537,0.021322,0.014763,9
6,124,0.8,0.02,8,50,200,15,0.1,3.0,0.8,0.00028,0.000121,0.000537,0.021322,0.014763,9
7,128,0.8,0.02,8,50,200,31,0.1,3.0,0.8,0.00028,0.000121,0.000537,0.021322,0.014763,9
8,132,0.8,0.02,8,50,200,63,0.1,3.0,0.8,0.00028,0.000121,0.000537,0.021322,0.014763,9
9,26,0.8,0.02,-1,50,200,15,0.0,3.0,0.8,0.00028,0.000119,0.000538,0.041011,0.039608,9

Best config id: 28
Best params: {'colsample_bytree': 0.8, 'learning_rate': 0.02, 'max_depth': -1, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 15, 'reg_alpha': 0.1, 'reg_lambda': 3.0, 'subsample': 0.8}

,SYMBOL,MSE,OLS_R2,OLS_Intercept,OLS_Slope,OLS_P_Value_Intercept,P_Value_Slope,n_samples
0,GC1 Comdty,0.000121,0.035097,0.000234,0.983318,0.135078,2.466002e-40,5175
1,BLQ2TRUU Index,0.000041,0.013150,0.000032,0.895443,0.793871,1.632517e-09,2981
2,GBPJPY Curncy,0.000055,0.014763,-0.000002,0.746275,0.983027,8.316961e-23,6711
3,M4EUHDVD Index,0.000156,0.023853,0.000236,0.748926,0.098241,3.857205e-34,6367
4,HFRXM Index,0.000017,0.006459,0.000016,0.738586,0.785369,1.834883e-07,4450
5,GB1M Index,0.001693,0.007675,0.000122,0.352679,0.919126,2.839745e-11,5991
6,QW2I Index,0.000003,0.000713,0.000073,0.324902,0.006583,3.266681e-02,6617
7,FNER Index,0.000281,0.046319,0.000199,0.809745,0.354291,2.115423e-66,6459
8,SPX Index,0.000152,0.043866,0.000202,0.978471,0.177851,6.649148e-63,6479

In [ ]:

# Optional exports
# search_df.to_csv('Resultats/lgbm_hyperparam_search_test_tickers.csv', index=False)
# best_per_ticker.to_csv('Resultats/lgbm_best_config_test_tickers_detail.csv', index=False)

In [4]:
# Run best params on ALL tickers
BEST_PARAMS = {
    "colsample_bytree": 0.8,
    "learning_rate": 0.02,
    "max_depth": 5,
    "min_child_samples": 50,
    "n_estimators": 200,
    "num_leaves": 15,
    "reg_alpha": 0.0,
    "reg_lambda": 1.0,
    "subsample": 0.8,
}
STEP_SIZE = 50
FOLD_SIZE = 200
results_all = []
for ticker in all_tickers:
    results_all.append(
        stats_forecasting_lgbm(
            df_all=df,
            name_ticker=ticker,
            model_params=BEST_PARAMS,
            feature_engineering=feature_engineering_rf,
            step_size=STEP_SIZE,
            fold_size=FOLD_SIZE,
        )
    )
df_lgbm_all = pd.DataFrame(results_all)
model_name = "LGBM_opti"
csv_name = f"Resultats/resultats_all_tickers_{model_name}.csv"
# Sauvegarde
df_lgbm_all.to_csv(csv_name, index=False)
display(df_lgbm_all.head())
print("Saved to:", csv_name)

c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
c:\Users\diane\time-series-pred\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

,SYMBOL,MSE,OLS_R2,OLS_Intercept,OLS_Slope,OLS_P_Value_Intercept,P_Value_Slope,n_samples
0,ADBF Index,0.000277,0.018154,0.000487,0.461741,0.089188,5.096172e-13,3061
1,ADCM Index,0.000528,0.069549,0.000220,0.760662,0.592385,2.075710e-43,2861
2,ADCT Index,0.000318,0.047996,0.000159,0.747637,0.596556,2.584879e-32,3054
3,ADEG Index,0.000799,0.032957,0.000134,0.663028,0.777170,4.539762e-21,2888
4,ADHC Index,0.000981,0.034551,0.001611,0.740987,0.301555,7.286464e-05,692

Saved to: Resultats/resultats_all_tickers_LGBM_opti.csv